# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_page(object):
    def setupUi(self, delete_page):
        delete_page.setObjectName("delete_page")
        delete_page.resize(908, 768)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/删除.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        delete_page.setWindowIcon(icon)
        delete_page.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(delete_page)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(430, 103, 251, 221))
        self.frame_7.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(85, 170, 127);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame = QtWidgets.QFrame(self.frame_7)
        self.frame.setGeometry(QtCore.QRect(10, 10, 231, 201))
        self.frame.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border-radius:5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.deleted_button = QtWidgets.QPushButton(self.frame)
        self.deleted_button.setGeometry(QtCore.QRect(65, 130, 101, 41))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.deleted_button.setFont(font)
        self.deleted_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(200, 200, 255);\n"
"    border:2px solid;\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 170, 255);\n"
"    border:2px solid;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 170, 255);\n"
"    border:2px solid;\n"
"    border:4px outset;\n"
"}")
        self.deleted_button.setObjectName("deleted_button")
        self.id_deleted_input = QtWidgets.QLineEdit(self.frame)
        self.id_deleted_input.setGeometry(QtCore.QRect(15, 70, 201, 40))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.id_deleted_input.setFont(font)
        self.id_deleted_input.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgb(0,0,0);\n"
"border-radius:0px;\n"
"")
        self.id_deleted_input.setPlaceholderText("")
        self.id_deleted_input.setObjectName("id_deleted_input")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(15, 40, 201, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(190, 0, 41, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.close_button_d = QtWidgets.QPushButton(self.frame_4)
        self.close_button_d.setGeometry(QtCore.QRect(10, 5, 26, 26))
        self.close_button_d.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(235, 113, 113);\n"
"    text-align:center;\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:13px;\n"
"}\n"
"QPushButton:hover {\n"
"    border:-4px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        self.close_button_d.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/关闭白.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button_d.setIcon(icon1)
        self.close_button_d.setObjectName("close_button_d")
        delete_page.setCentralWidget(self.centralwidget)

        self.retranslateUi(delete_page)
        QtCore.QMetaObject.connectSlotsByName(delete_page)
        delete_page.setTabOrder(self.id_deleted_input, self.deleted_button)
        delete_page.setTabOrder(self.deleted_button, self.close_button_d)

    def retranslateUi(self, delete_page):
        _translate = QtCore.QCoreApplication.translate
        delete_page.setWindowTitle(_translate("delete_page", "MainWindow"))
        self.deleted_button.setText(_translate("delete_page", "删除书籍"))
        self.label.setText(_translate("delete_page", "输入待删除书籍的编号"))
import res_rc
