# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_page(object):
    def setupUi(self, login_page):
        login_page.setObjectName("login_page")
        login_page.setEnabled(True)
        login_page.resize(750, 558)
        login_page.setStyleSheet("")
        self.frame = QtWidgets.QFrame(login_page)
        self.frame.setGeometry(QtCore.QRect(30, 20, 301, 501))
        self.frame.setStyleSheet("border-image: url(:/image/image/1.PNG);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(login_page)
        self.frame_2.setGeometry(QtCore.QRect(330, 20, 391, 501))
        self.frame_2.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.quit_button = QtWidgets.QPushButton(self.frame_2)
        self.quit_button.setGeometry(QtCore.QRect(200, 390, 140, 60))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.quit_button.setFont(font)
        self.quit_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 85, 127);\n"
"    text-align:center;\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"    border:-3px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}")
        self.quit_button.setAutoDefault(False)
        self.quit_button.setObjectName("quit_button")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 341, 101))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pwd_input = QtWidgets.QLineEdit(self.frame_2)
        self.pwd_input.setGeometry(QtCore.QRect(40, 260, 301, 61))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(16)
        self.pwd_input.setFont(font)
        self.pwd_input.setStyleSheet("border-bottom:2px solid rgb(0,0,0);\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"")
        self.pwd_input.setText("")
        self.pwd_input.setFrame(False)
        self.pwd_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_input.setObjectName("pwd_input")
        self.login_button = QtWidgets.QPushButton(self.frame_2)
        self.login_button.setGeometry(QtCore.QRect(40, 390, 140, 60))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 85, 0);\n"
"    text-align:center;\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"    border:-3px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        self.login_button.setAutoDefault(True)
        self.login_button.setDefault(False)
        self.login_button.setObjectName("login_button")
        self.user_input = QtWidgets.QLineEdit(self.frame_2)
        self.user_input.setGeometry(QtCore.QRect(40, 150, 301, 61))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(16)
        self.user_input.setFont(font)
        self.user_input.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgb(0,0,0);\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"")
        self.user_input.setFrame(False)
        self.user_input.setClearButtonEnabled(False)
        self.user_input.setObjectName("user_input")

        self.retranslateUi(login_page)
        QtCore.QMetaObject.connectSlotsByName(login_page)
        login_page.setTabOrder(self.user_input, self.pwd_input)
        login_page.setTabOrder(self.pwd_input, self.login_button)
        login_page.setTabOrder(self.login_button, self.quit_button)

    def retranslateUi(self, login_page):
        _translate = QtCore.QCoreApplication.translate
        login_page.setWindowTitle(_translate("login_page", "登录"))
        self.quit_button.setText(_translate("login_page", "退出系统"))
        self.label_3.setText(_translate("login_page", "图书信息管理系统"))
        self.pwd_input.setPlaceholderText(_translate("login_page", "请在此输入密码"))
        self.login_button.setText(_translate("login_page", "登录系统"))
        self.user_input.setPlaceholderText(_translate("login_page", "请在此输入账号"))
import res_rc
