# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_book_mainpage(object):
    def setupUi(self, book_mainpage):
        book_mainpage.setObjectName("book_mainpage")
        book_mainpage.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(book_mainpage)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(100, 20, 801, 31))
        self.frame_6.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-top-right-radius:15px;\n"
"border-top-left-radius:15px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.close_button = QtWidgets.QPushButton(self.frame_6)
        self.close_button.setGeometry(QtCore.QRect(770, 2, 26, 26))
        self.close_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(235, 113, 113);\n"
"    text-align:center;\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:13px;\n"
"}\n"
"QPushButton:hover {\n"
"    border:-4px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        self.close_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/关闭白.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon)
        self.close_button.setObjectName("close_button")
        self.mini_button = QtWidgets.QPushButton(self.frame_6)
        self.mini_button.setGeometry(QtCore.QRect(730, 2, 26, 26))
        self.mini_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(235, 113, 113);\n"
"    text-align:center;\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:13px;\n"
"}\n"
"QPushButton:hover {\n"
"    border:-4px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"\n"
"")
        self.mini_button.setIconSize(QtCore.QSize(16, 16))
        self.mini_button.setObjectName("mini_button")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(100, 670, 801, 31))
        self.frame_5.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border-bottom-right-radius:15px;\n"
"border-bottom-left-radius:15px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(100, 50, 801, 621))
        self.frame.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(10, 140, 781, 421))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(12)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(190)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(34)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(202, 90, 192, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #99cccc")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(584, 90, 192, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: #999999")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.book_quantity = QtWidgets.QLineEdit(self.frame)
        self.book_quantity.setGeometry(QtCore.QRect(10, 570, 671, 51))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.book_quantity.setFont(font)
        self.book_quantity.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.book_quantity.setFocusPolicy(QtCore.Qt.NoFocus)
        self.book_quantity.setText("")
        self.book_quantity.setFrame(False)
        self.book_quantity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.book_quantity.setObjectName("book_quantity")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(393, 90, 192, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: #cc9966")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_1 = QtWidgets.QLabel(self.frame)
        self.label_1.setGeometry(QtCore.QRect(10, 90, 193, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("background-color: #cccc99")
        self.label_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_1.setScaledContents(False)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setOpenExternalLinks(False)
        self.label_1.setObjectName("label_1")
        self.sort_button = QtWidgets.QPushButton(self.frame)
        self.sort_button.setGeometry(QtCore.QRect(681, 25, 112, 41))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.sort_button.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/排序.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sort_button.setIcon(icon1)
        self.sort_button.setIconSize(QtCore.QSize(20, 20))
        self.sort_button.setObjectName("sort_button")
        self.update_button = QtWidgets.QPushButton(self.frame)
        self.update_button.setGeometry(QtCore.QRect(523, 25, 152, 41))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.update_button.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/更新.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.update_button.setIcon(icon2)
        self.update_button.setIconSize(QtCore.QSize(20, 20))
        self.update_button.setObjectName("update_button")
        self.search_button = QtWidgets.QPushButton(self.frame)
        self.search_button.setGeometry(QtCore.QRect(169, 25, 112, 41))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.search_button.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/查询.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon3)
        self.search_button.setIconSize(QtCore.QSize(20, 20))
        self.search_button.setObjectName("search_button")
        self.show_button = QtWidgets.QPushButton(self.frame)
        self.show_button.setGeometry(QtCore.QRect(11, 25, 152, 41))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.show_button.setFont(font)
        self.show_button.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/显示.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_button.setIcon(icon4)
        self.show_button.setIconSize(QtCore.QSize(20, 20))
        self.show_button.setCheckable(False)
        self.show_button.setChecked(False)
        self.show_button.setAutoDefault(False)
        self.show_button.setDefault(False)
        self.show_button.setFlat(False)
        self.show_button.setObjectName("show_button")
        self.insert_button = QtWidgets.QPushButton(self.frame)
        self.insert_button.setGeometry(QtCore.QRect(287, 25, 112, 41))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.insert_button.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/添加.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insert_button.setIcon(icon5)
        self.insert_button.setIconSize(QtCore.QSize(20, 20))
        self.insert_button.setObjectName("insert_button")
        self.delete_button = QtWidgets.QPushButton(self.frame)
        self.delete_button.setGeometry(QtCore.QRect(405, 25, 112, 41))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.delete_button.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/删除.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon6)
        self.delete_button.setIconSize(QtCore.QSize(20, 20))
        self.delete_button.setObjectName("delete_button")
        self.sort_button.raise_()
        self.update_button.raise_()
        self.search_button.raise_()
        self.show_button.raise_()
        self.insert_button.raise_()
        self.delete_button.raise_()
        self.tableWidget.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.book_quantity.raise_()
        self.label_3.raise_()
        self.label_1.raise_()
        self.deduplicate_button = QtWidgets.QPushButton(self.centralwidget)
        self.deduplicate_button.setGeometry(QtCore.QRect(790, 630, 101, 41))
        self.deduplicate_button.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    font: 12pt \"方正准圆_GBK\";\n"
"    background-color: rgb(204, 204, 153);\n"
"    text-align:center;\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:13px;\n"
"}\n"
"QPushButton:hover {\n"
"    border:-4px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/去重.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deduplicate_button.setIcon(icon7)
        self.deduplicate_button.setIconSize(QtCore.QSize(25, 25))
        self.deduplicate_button.setObjectName("deduplicate_button")
        book_mainpage.setCentralWidget(self.centralwidget)

        self.retranslateUi(book_mainpage)
        QtCore.QMetaObject.connectSlotsByName(book_mainpage)

    def retranslateUi(self, book_mainpage):
        _translate = QtCore.QCoreApplication.translate
        book_mainpage.setWindowTitle(_translate("book_mainpage", "MainWindow"))
        self.mini_button.setText(_translate("book_mainpage", "--"))
        self.tableWidget.setSortingEnabled(False)
        self.label_2.setText(_translate("book_mainpage", "书籍名称"))
        self.label_4.setText(_translate("book_mainpage", "书籍价格"))
        self.label_3.setText(_translate("book_mainpage", "书籍作者"))
        self.label_1.setText(_translate("book_mainpage", "书籍编号"))
        self.sort_button.setText(_translate("book_mainpage", "价格排序"))
        self.update_button.setText(_translate("book_mainpage", "修改书籍信息"))
        self.search_button.setText(_translate("book_mainpage", "查询书籍"))
        self.show_button.setText(_translate("book_mainpage", "显示全部书籍"))
        self.insert_button.setText(_translate("book_mainpage", "添加书籍"))
        self.delete_button.setText(_translate("book_mainpage", "删除书籍"))
        self.deduplicate_button.setText(_translate("book_mainpage", "书籍去重"))
import res_rc
