# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_page(object):
    def setupUi(self, update_page):
        update_page.setObjectName("update_page")
        update_page.setEnabled(True)
        update_page.resize(988, 744)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/更新.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        update_page.setWindowIcon(icon)
        update_page.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(update_page)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(600, 90, 381, 461))
        self.frame_7.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(85, 170, 127);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame = QtWidgets.QFrame(self.frame_7)
        self.frame.setGeometry(QtCore.QRect(10, 10, 361, 441))
        self.frame.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border-radius:5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(30, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.price_input = QtWidgets.QLineEdit(self.frame)
        self.price_input.setGeometry(QtCore.QRect(100, 340, 220, 40))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.price_input.setFont(font)
        self.price_input.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgb(0,0,0);\n"
"border-radius:0px;\n"
"")
        self.price_input.setObjectName("price_input")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 190, 66, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.writer_input = QtWidgets.QLineEdit(self.frame)
        self.writer_input.setGeometry(QtCore.QRect(100, 290, 220, 40))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.writer_input.setFont(font)
        self.writer_input.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgb(0,0,0);\n"
"border-radius:0px;\n"
"")
        self.writer_input.setObjectName("writer_input")
        self.data_updated = QtWidgets.QLineEdit(self.frame)
        self.data_updated.setGeometry(QtCore.QRect(100, 100, 220, 40))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.data_updated.setFont(font)
        self.data_updated.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgb(0,0,0);\n"
"border-radius:0px;\n"
"")
        self.data_updated.setObjectName("data_updated")
        self.id_input = QtWidgets.QLineEdit(self.frame)
        self.id_input.setGeometry(QtCore.QRect(100, 190, 220, 40))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.id_input.setFont(font)
        self.id_input.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgb(0,0,0);\n"
"border-radius:0px;\n"
"\n"
"")
        self.id_input.setObjectName("id_input")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 40, 171, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 291, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.name_input = QtWidgets.QLineEdit(self.frame)
        self.name_input.setGeometry(QtCore.QRect(100, 240, 220, 40))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.name_input.setFont(font)
        self.name_input.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgb(0,0,0);\n"
"border-radius:0px;\n"
"\n"
"")
        self.name_input.setObjectName("name_input")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(320, 0, 41, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.close_button_u = QtWidgets.QPushButton(self.frame_4)
        self.close_button_u.setGeometry(QtCore.QRect(10, 5, 26, 26))
        self.close_button_u.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(235, 113, 113);\n"
"    text-align:center;\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:13px;\n"
"}\n"
"QPushButton:hover {\n"
"    border:-4px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        self.close_button_u.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/关闭白.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button_u.setIcon(icon1)
        self.close_button_u.setObjectName("close_button_u")
        self.updated_button = QtWidgets.QPushButton(self.frame_7)
        self.updated_button.setGeometry(QtCore.QRect(150, 400, 111, 41))
        font = QtGui.QFont()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(14)
        self.updated_button.setFont(font)
        self.updated_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(100, 170, 255);\n"
"    border:2px solid;\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 170, 255);\n"
"    border:2px solid;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 170, 255);\n"
"    border:2px solid;\n"
"    border:4px outset;\n"
"}")
        self.updated_button.setObjectName("updated_button")
        update_page.setCentralWidget(self.centralwidget)

        self.retranslateUi(update_page)
        QtCore.QMetaObject.connectSlotsByName(update_page)
        update_page.setTabOrder(self.data_updated, self.id_input)
        update_page.setTabOrder(self.id_input, self.name_input)
        update_page.setTabOrder(self.name_input, self.writer_input)
        update_page.setTabOrder(self.writer_input, self.price_input)
        update_page.setTabOrder(self.price_input, self.updated_button)
        update_page.setTabOrder(self.updated_button, self.close_button_u)

    def retranslateUi(self, update_page):
        _translate = QtCore.QCoreApplication.translate
        update_page.setWindowTitle(_translate("update_page", "MainWindow"))
        self.label_7.setText(_translate("update_page", "书籍编号"))
        self.price_input.setPlaceholderText(_translate("update_page", "None"))
        self.label_3.setText(_translate("update_page", "书籍编号"))
        self.label_4.setText(_translate("update_page", "书籍名称"))
        self.label_5.setText(_translate("update_page", "书籍作者"))
        self.label_6.setText(_translate("update_page", "书籍价格"))
        self.writer_input.setPlaceholderText(_translate("update_page", "None"))
        self.data_updated.setPlaceholderText(_translate("update_page", "待更新书籍的编号"))
        self.id_input.setPlaceholderText(_translate("update_page", "None"))
        self.label.setText(_translate("update_page", "输入需更新数据的"))
        self.label_2.setText(_translate("update_page", "输入新数据"))
        self.name_input.setPlaceholderText(_translate("update_page", "None"))
        self.updated_button.setText(_translate("update_page", "更新数据"))
import res_rc
